# Generated by Django 5.0 on 2023-12-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
