# Generated by Django 5.0 on 2023-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_remove_label_contents_remove_label_disparity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
