# Generated by Django 5.0 on 2023-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_label_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
