# Generated by Django 5.0 on 2023-12-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_label_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='compare',
            field=models.TextField(blank=True),
        ),
    ]
